# Generated by Django 6.0 on 2026-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_total', models.IntegerField(default=0)),
                ('espacios_disponibles', models.IntegerField(default=0)),
            ],
        ),
    ]
