# Generated by Django 6.0.2 on 2026-03-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='parqueaderos/')),
                ('vehiculos_cola', models.IntegerField()),
                ('flujo_vehiculos', models.FloatField(help_text='Vehículos por minuto')),
                ('tiempo_espera', models.IntegerField(help_text='Tiempo estimado en minutos')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
