# Generated by Django 6.0.2 on 2026-03-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo_espera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempoespera',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tiempoespera',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tiempoespera',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='tiempoespera',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='flujo_vehiculos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='tiempo_espera',
            field=models.IntegerField(editable=False),
        ),
    ]
