# Generated by Django 6.0.2 on 2026-03-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo_espera', '0002_remove_tiempoespera_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempoespera',
            name='nombre',
            field=models.CharField(default='Parqueadero', max_length=100),
            preserve_default=False,
        ),
    ]
