# Generated by Django 6.0.2 on 2026-03-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo_espera', '0003_tiempoespera_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempoespera',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tiempoespera',
            name='parqueadero',
            field=models.CharField(choices=[('central', 'Parqueadero Central'), ('ingenieros', 'Parqueadero Ingenieros'), ('idiomas', 'Parqueadero Idiomas')], default='parqueo', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='flujo_vehiculos',
            field=models.FloatField(help_text='Vehículos por minuto'),
        ),
    ]
