# Generated by Django 6.0.2 on 2026-03-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo_espera', '0004_remove_tiempoespera_nombre_tiempoespera_parqueadero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiempoespera',
            options={'verbose_name': 'Tiempo de Espera', 'verbose_name_plural': 'Tiempos de Espera'},
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='flujo_vehiculos',
            field=models.FloatField(verbose_name='Flujo (veh/min)'),
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='parqueadero',
            field=models.CharField(choices=[('central', 'Parqueadero Central'), ('ing', 'Parqueadero Ingenieros'), ('idiomas', 'Parqueadero Idiomas')], max_length=20, unique=True, verbose_name='Parqueadero'),
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='tiempo_espera',
            field=models.IntegerField(editable=False, verbose_name='Tiempo de espera (min)'),
        ),
        migrations.AlterField(
            model_name='tiempoespera',
            name='vehiculos_cola',
            field=models.IntegerField(verbose_name='Vehículos en cola'),
        ),
    ]
