# Generated by Django 6.0 on 2026-03-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_celda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celda',
            name='parqueadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.parqueadero'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='capacidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
