# Generated by Django 6.0.3 on 2026-03-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('esta_ocupada', models.BooleanField(default=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='monitoreo.parqueadero')),
            ],
        ),
    ]
