# Generated by Django 6.0.2 on 2026-03-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_total', models.PositiveIntegerField()),
                ('espacios_disponibles', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
                'ordering': ['-espacios_disponibles'],
            },
        ),
    ]
