# Generated by Django 6.0.2 on 2026-03-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parqueadero',
            options={'ordering': ['-espacios_disponibles']},
        ),
    ]
