# Generated by Django 6.0.2 on 2026-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_alter_parqueadero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Parqueadero')),
                ('total_spaces', models.IntegerField(verbose_name='Capacidad Total')),
                ('available_spaces', models.IntegerField(verbose_name='Espacios Disponibles')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen (Opcional)')),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
            },
        ),
        migrations.DeleteModel(
            name='Parqueadero',
        ),
    ]
